name: raven_for_nitc
description: An event notifier for NIT Calicut
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.2
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.0
  flutter_speed_dial: ^6.2.0
  google_sign_in: ^5.4.4
  image_picker: ^0.8.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: '^0.11.0'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/mess.json

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo.png'
